spring:
  application:
    name: loom-demo
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/loom_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 400
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  sql:
    init:
      mode: always
  data:
    jdbc:
      repositories:
        enabled: true

logging:
  level:
    org.springframework.jdbc.core: DEBUG
